provider: huggingface
model: microsoft/Phi-3-mini-4k-instruct
params:
  backend: pipeline
  task: text-generation
  device_map: auto

  # Generation
  max_new_tokens: 2048
  temperature: 0

  # Model loading
  model_kwargs: {}

