provider: huggingface
model: microsoft/Phi-4-mini-reasoning
params:
  backend: pipeline
  task: text-generation
  device_map: cuda:0

  # Generation
  max_new_tokens: 4096
  temperature: 0

  # Model loading
  model_kwargs:
    torch_dtype: bfloat16

